MODEL:
  TYPE: nas
  NUM_CLASSES: 10
  LOSS_FUN: label_smoothed_cross_entropy
  LABEL_SMOOTHING_EPS: 0.1
NAS:
  GENOTYPE: cifar10_train_small
  WIDTH: 36
  DEPTH: 20
  AUX: True
  DROP_PROB: 0.2
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  MAX_EPOCH: 600
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
  WARMUP_EPOCHS: 5
  ITER_LR: False
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 256
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: results/cifar10_train_small/eval
LOG_PERIOD: 10