MODEL:
  TYPE: nas_search
  NUM_CLASSES: 10
NAS:
  GENOTYPE: darts_v1
  WIDTH: 16
  DEPTH: 8
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
  ITER_LR: False
  ARCH_BASE_LR: 0.0003
  ARCH_WEIGHT_DECAY: 0.001
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 64
  IM_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  PORTION: 0.0
  DATAPORTION: 0.1
TEST:
  BATCH_SIZE: 64
  IM_SIZE: 32
NUM_GPUS: 2
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True

